### PR TITLE
Add OAuth flow to the library

### PR DESCRIPTION
**Pull request by david-martin**
See README for info on how OAuth is used.

### CODE REVIEW

**Comment by david-martin** [comment]
@aidenkeating I'd like to add a 401 or 403 handler (not sure which is accurate for invalid/expired access token yet) to all fetch calls,
and restart the oauth flow automatically if that happens.
Expect another commit

**Comment by aidenkeating** [comment]
@david-martin Looks like `client-oauth2` hasn't been added to `yarn.lock`

**Comment by david-martin** [comment]
@aidenkeating I've pushed another update (rebased).
I've decided to move away for heavy use of statics and the dependency on the `window.OPENSHIFT_CONFIG` global.
All config is now passed into the constructor.
This avoids the mix of config that I was proposing first, with mockData being set in the constructor, and all other config in the global.
Plus it makes it easier to test by allowing passing in test settings (instead of manipulating globals in tests :nauseated_face: )

**Comment by david-martin** [comment]
@aidenkeating I'm closing this as the changes are directly in the development branch of the tutorial-web-app now.
Thanks for the review.

I think there may be a useful library still that we could extract, which includes just the openshift auth & API bits (not the walkthrough bits).
I'll let you know if I propose anything in future.

**Pull request closed without merging**
